### ISSUE TITLE
One of the three themes is missing from the repo

### ISSUE THREAD

**Issue by bmn001** [ebzero/garlic-onion-skraper-mix#2]
`README.md` showcases three themes: **Full Height Mix**, **3-Images Mix**, and **Full Screen Mix**.

Looking at the directories...
`Garlic-Onion-Mix`: contains "Full Height Mix" for both Garlic and Onion
`'3 Image Mix - Garlic`: contains "3-Images Mix" for Garlic
`'3 Image Mix - Onion`: contains "3-Images Mix" for Onion

"Full Screen Mix" doesn't seem to exist in this repo at all.

**Comment by ebzero** [comment]
Full Screen Mix is not mine.  It is in another repo as stated here:

Check out [this](https://github.com/timault/Garlic-Os-Skraper-) github project by timault to get these awesome preview images (Garlic Only)
